### ISSUE TITLE
Create a major tag which points to the latest major version

### ISSUE THREAD

**Issue by KevinRohn** [mukunku/tag-exists-action#10]
can you make a `v1` tag in this repository which will point to the latest `v1` version of this action so we can use it in our workflows like this:

```yml
- uses: mukunku/tag-exists-action@v1
  id: check_tag
  with: 
    tag: 'tag-to-search-for'

- run: echo ${{ steps.check_tag.outputs.exists }}
```

And there won't be any need to update all workflows when a non-breaking change is introduced.
